### ISSUE TITLE
Light mode display

### ISSUE THREAD

**Issue by samdmarshall** [Kwpolska/upass#16]
Hi, I was wondering if this project could be updated to support a "light" mode of the current color display. It seems that the current hard-coded color values were picked based on a dark background terminal, and is very hard to read on mine:
<img width="311" alt="screen shot 2017-03-19 at 21 42 14" src="https://cloud.githubusercontent.com/assets/1087718/24086848/441a36c4-0ced-11e7-88c6-8edb487706b6.png">

**Comment by Kwpolska** [comment]
Done, and it doesn’t even need any special options: the scheme now looks okay on both black and white terminals. I’ll release v0.1.8 now.

**Comment by samdmarshall** [comment]
thanks, this is much better now!
