### ISSUE TITLE
upass copy to clipboard stoped working since upgrade to Ubuntu 19.10

### ISSUE THREAD

**Issue by lowk3y** [Kwpolska/upass#24]
Copy to clipboard stopped working, but when it does copy it copies some random UTF characters .. 

Using upass from Ubuntu repo / and this weird behaviors started when upgraded from Ubuntu 19.04 to 19.10.

**Comment by Kwpolska** [comment]
Open a `python3` shell and run:

```py
import pyperclip
pyperclip.determine_clipboard()
```

What does it output?

Also, are you using Xorg or Wayland?

**Comment by lowk3y** [comment]
this is the output 
```
python3
Python 3.7.5 (default, Nov 20 2019, 09:21:52) 
[GCC 9.2.1 20191008] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyperclip
>>> pyperclip.determine_clipboard()
(<function init_gi_clipboard.<locals>.copy_gi at 0x7f7e9c6a4d40>, <function init_gi_clipboard.<locals>.paste_gi at 0x7f7e9c69c680>)
```

Xorg/X11 as far as I can tell .. Wayland is still not production-ready, or am I missing something?

**Comment by Kwpolska** [comment]
The `gi` copy method is not part of the standard Python package, it’s a custom ~~Ubuntu~~ Debian patch. Run `python3` and then:

```py
import pyperclip
pyperclip.copy('hello world')
pyperclip.paste()
```

Do you still get random garbage when you paste? Does random garbage appear when you paste with `pyperclip.paste()`?

**Comment by lowk3y** [comment]
That's the output

```
Python 3.7.5 (default, Nov 20 2019, 09:21:52) 
[GCC 9.2.1 20191008] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyperclip
>>> pyperclip.copy('hello world')
>>> pyperclip.paste()
'hello world'
>>> 
```

**Comment by Kwpolska** [comment]
Do you get random garbage when you run this and then try to paste in another app?

**Comment by lowk3y** [comment]
I get nothing .. as nothing is copied

**Comment by Kwpolska** [comment]
Everything points to this being an issue with Debian’s patch for pyperclip that adds `gi`/GTK+3 support being broken. Please report a bug to Ubuntu upstream (or Debian?).

Ubuntu bugs for python-pyperclip: https://launchpad.net/ubuntu/+source/python-pyperclip/+bugs
