### ISSUE TITLE
When copying password with "c", the password gets displayed afterwards

### ISSUE THREAD

**Issue by matthiasbeyer** [Kwpolska/upass#3]
This is a bad "bug" IMHO, as I don't want to display the password after copying it to clipboard.

Reproduce:
- Select a password (but don't open the menu for it)
- Hit `c`
- Password gets copied to the clipboard, screen refreshes and shows password in the first line

In fact, the password gets even displayed when you enter the menu for the password, **and** if you select the menu entry "copy" and copy it with the menu entry.

When I want to copy the password, it should _never ever_ be shown afterwards!

**Comment by Kwpolska** [comment]
Should be an easy fix, will get on it.
