### ISSUE TITLE
Option to sort the entries

### ISSUE THREAD

**Issue by ghost** [Kwpolska/upass#32]
It would be nice to have a config entry, for sorting the entries showing by upass. 

In my case I can not see any alphabetically or other logic upass displays my content of .password-store. 
Also I can see subfolders in the main screen (the root-folder) wich is something I don't want. 

Thanks for your attention.
;)

**Comment by Kwpolska** [comment]
The order you see entries in is whatever `os.listdir` returns, i.e. random. I changed it to alphabetical order (although I don’t plan any new releases soon, so you might need to apply it manually to your install).

As for the subfolders part, I think this behavior is sensible for many password stores, so I don’t think it’s worth changing it.

**Comment by ghost** [comment]
@Kwpolska Thank you for that change.
